[package]
authors = ["Todd Nguyen"]
edition = "2018"
name = "javajar"
version = "0.1.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
winres = "*"

[dependencies]
env_logger = "0.8"
log = "0.4"

[profile.release]
lto = true
